name: copytyping-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - anndata
  - matplotlib-base
  - numpy
  - pandas
  - pyyaml
  - scanpy
  - scikit-learn
  - scipy
  - seaborn
  - squidpy>=1.4.1
