name: copytyping-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - bcftools>=1.19
  - bedtools
  - tabix
  - matplotlib-base
  - numpy
  - pandas
  - pysam
  - pyranges
  - scikit-learn
  - scipy
  - seaborn
  - pip
  - pip:
    - PyYAML

